# Generated by Django 2.0.1 on 2018-04-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180415_0312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('id', 'author')},
        ),
    ]
